### ISSUE TITLE
II_faculty-format

### ISSUE THREAD

**Issue by datalorax** [ResearchTransparency/rr_aera19#4]
Not sure if what I did is what they're looking for but I did my best. It would be great if you could look it over and maybe add some to your bio part a bit more. I *think* I addressed everything they want but I'm really not sure.

**Comment by jrosen48** [comment]
Had to look at this again, because it's a bit of an odd part of the proposal (now [here](https://github.com/ResearchTransparency/rr_aera19/blob/master/planning/aera2019_Professional_Development_Instructions.pdf) in the planning directory) - it seems like something they could get from the submission system just as well. Anyway, from the doc, to my read it looks like they only want "List of instructor(s), with institutional affiliation(s) and e-mail address(es)". 

I also see that they want a "One-page relevant CV for each instructor" and "Other supporting materials".

In any case, I think this is helpful information to include and don't think it could hurt. I guess I wonder if we could move some of it / label some of this as supporting materials? What do you think of all this?

**Comment by jrosen48** [comment]
I will add a bit to my section, as it sounds like we'll use this in any case.

**Comment by datalorax** [comment]
Sure, we can move it to supporting docs. That sounds like a good plan.

**Comment by jrosen48** [comment]
I think I've addressed this (and mentioned in #6) and we can close?
